# Generated by Django 4.2.1 on 2023-05-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stumodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('s_regno', models.IntegerField()),
                ('s_m1', models.FloatField()),
                ('s_m2', models.FloatField()),
            ],
        ),
    ]
